attributes:
- beginString: '[$][ ]'
  endString: '[\n|\\]'
  ignoreCase: false
  regularExpression: true
characters:
- beginString: '[<|>|?|+|\-|*|/|=|\\|;|:|"|''|.|,|~|`|!|@|%|^|&|$|*|(|)]'
  ignoreCase: false
  regularExpression: true
commands: []
commentDelimiters:
  beginDelimiter: /*
  endDelimiter: '*/'
  inlineDelimiter: '# '
comments:
- beginString: (\s#)|(^#)
  endString: $
  ignoreCase: false
  regularExpression: true
completions: []
extensions:
- keyString: txt
- keyString: gd
interpreters: []
keywords:
- beginString: clamp
  ignoreCase: true
  regularExpression: false
- beginString: class
  ignoreCase: true
  regularExpression: false
- beginString: const
  ignoreCase: true
  regularExpression: false
- beginString: enum
  ignoreCase: true
  regularExpression: false
- beginString: for
  ignoreCase: true
  regularExpression: false
- beginString: func
  ignoreCase: true
  regularExpression: false
- beginString: if
  ignoreCase: true
  regularExpression: false
- beginString: return
  ignoreCase: true
  regularExpression: false
- beginString: static
  ignoreCase: true
  regularExpression: false
- beginString: switch
  ignoreCase: true
  regularExpression: false
metadata:
  author: fistnine
  lastModified: '2022-06-19'
  version: '1.0'
numbers:
- beginString: '[0-9]'
  regularExpression: true
outlineMenu:
- beginString: ^(#.+)$
  bold: true
  ignoreCase: true
- beginString: ^([\t ]+#.+)$
  ignoreCase: true
  italic: true
  underline: false
strings:
- beginString: '"'
  endString: '"'
  ignoreCase: true
  regularExpression: false
- beginString: 《
  endString: 》
  ignoreCase: true
  regularExpression: false
types:
- beginString: error
  ignoreCase: true
  regularExpression: false
- beginString: string
  ignoreCase: true
  regularExpression: false
- beginString: var
  ignoreCase: true
  regularExpression: false
- beginString: vector
  ignoreCase: true
  regularExpression: true
- beginString: void
  ignoreCase: true
  regularExpression: false
values:
- beginString: 'false'
  ignoreCase: true
  regularExpression: false
- beginString: 'true'
  ignoreCase: true
  regularExpression: false
variables: []
