attributes:
- beginString: '[$][ ]'
  endString: '[\n|\\]'
  ignoreCase: false
  regularExpression: true
characters:
- beginString: '[<|>|?|+|\-|*|/|=|\\|;|:|"|''|.|,|~|`|!|@|%|^|&|$|*|(|)]'
  ignoreCase: false
  regularExpression: true
commands: []
commentDelimiters:
  beginDelimiter: /*
  endDelimiter: '*/'
  inlineDelimiter: '# '
comments:
- beginString: (\s#)|(^#)
  endString: $
  ignoreCase: false
  regularExpression: true
completions: []
extensions:
- keyString: txt
- keyString: gd
interpreters: []
keywords:
- beginString: ^clamp|\t+clamp|\s+clamp
  ignoreCase: true
  regularExpression: true
- beginString: ^class|\t+class|\s+class
  ignoreCase: true
  regularExpression: true
- beginString: ^const|\t+const|\s+const
  ignoreCase: true
  regularExpression: true
- beginString: ^enum|\t+enum|\s+enum
  ignoreCase: true
  regularExpression: true
- beginString: ^for|\t+for|\s+for
  ignoreCase: true
  regularExpression: true
- beginString: ^func|\t+func|\s+func
  ignoreCase: true
  regularExpression: true
- beginString: ^if|\t+if|\s+if
  ignoreCase: true
  regularExpression: true
- beginString: ^return|\t+return|\s+return
  ignoreCase: true
  regularExpression: true
- beginString: ^static|\t+static|\s+static
  ignoreCase: true
  regularExpression: true
- beginString: ^switch|\t+switch|\s+switch
  ignoreCase: true
  regularExpression: true
metadata:
  author: fistnine
  lastModified: '2022-06-19'
  version: '1.0'
numbers:
- beginString: '[0-9]'
  regularExpression: true
outlineMenu:
- beginString: ^(#.+)$
  bold: true
  ignoreCase: true
- beginString: ^([\t ]+#.+)$
  ignoreCase: true
  italic: true
  underline: false
strings:
- beginString: '"'
  endString: '"'
  ignoreCase: true
  regularExpression: false
- beginString: 《
  endString: 》
  ignoreCase: true
  regularExpression: false
types:
- beginString: error
  ignoreCase: true
  regularExpression: false
- beginString: string
  ignoreCase: true
  regularExpression: false
- beginString: var
  ignoreCase: true
  regularExpression: false
- beginString: vector
  ignoreCase: true
  regularExpression: true
- beginString: void
  ignoreCase: true
  regularExpression: false
values:
- beginString: 'false'
  ignoreCase: true
  regularExpression: false
- beginString: 'true'
  ignoreCase: true
  regularExpression: false
variables: []
